<?php

class ReCaptcha {
    const SITE_KEY = '6Le5oFQsAAAAAHU-Fy3CB9jGJqJq6j51omSnCh0_';
    const SECRET_KEY = '6Le5oFQsAAAAAJExhyk42DHC7mVaYg_0xPxRTkdj';
    const VERIFY_URL = 'https://www.google.com/recaptcha/api/siteverify';

    /**
     * Verifies the reCAPTCHA token.
     *
     * @param string $token The token generated by the frontend.
     * @param string $action The action name for verification (optional).
     * @param float $threshold The minimum score required (default 0.5).
     * @return bool|array Returns true if successful, or an array/false on failure.
     */
    public static function verify($token, $action = null, $threshold = 0.5) {
        if (empty($token)) {
            return false;
        }

        $postData = http_build_query([
            'secret' => self::SECRET_KEY,
            'response' => $token,
            'remoteip' => $_SERVER['REMOTE_ADDR'] ?? '127.0.0.1'
        ]);

        $error = null;
        $response = static::sendRequest($postData, $error);

        if ($error) {
            error_log("ReCaptcha CURL Error: " . $error);
            return false;
        }

        $result = json_decode($response, true);

        if (isset($result['success']) && $result['success'] == true) {
            if (isset($result['score']) && $result['score'] >= $threshold) {
                // Optional: Check action name
                if ($action && isset($result['action']) && $result['action'] !== $action) {
                    error_log("ReCaptcha Action Mismatch: Expected $action, got " . $result['action']);
                    return false;
                }
                return true;
            } else {
                error_log("ReCaptcha Score Low: " . ($result['score'] ?? 'N/A'));
                return false;
            }
        }

        error_log("ReCaptcha Failed: " . json_encode($result));
        return false;
    }

    /**
     * Sends the POST request to the reCAPTCHA API.
     * Separated to allow overriding in tests via Late Static Binding.
     *
     * @param string $postData
     * @param string|null &$error
     * @return string|false
     */
    protected static function sendRequest($postData, &$error) {
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, self::VERIFY_URL);
        curl_setopt($ch, CURLOPT_POST, true);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $postData);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, true);

        $response = curl_exec($ch);
        $error = curl_error($ch);
        curl_close($ch);

        return $response;
    }

    public static function getSiteKey() {
        return self::SITE_KEY;
    }
}
